spring:
    application:
        name: expense-service
    hibernate:
        hbm2ddl:
            auto: create
    jpa:
        show-sql: true
        hibernate:  
            ddl-auto: create  
            database-platform: org.hibernate.dialect.PostgreSQLDialect  
        
        #hibernate:  
        #    ddl-auto: create  
        #    database-platform: org.hibernate.dialect.H2Dialect
    #datasource:  
        #url: jdbc:h2:mem:expense-db
    datasource:  
        url: "jdbc:postgresql://${JDBC_DATABASE_URL:expense-service:5432}/expense_db"  
        username: postgres  
        password: postgres


eureka:
    client:
        registerWithEureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://$"{EUREKA_URL:eureka:8761}/eureka
    instance:
        hostname: localhost